name: Quick scrape test
on:
  push:
env:
  RUST_BACKTRACE: "1"
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --all-features
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Build release target
        run: cargo build --release
      - name: Upload compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: hotprices-au-rs
          path: ./target/release/hotprices-au-rs
  scrape-woolies:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a release binary
        uses: actions/download-artifact@v4
        with:
          name: hotprices-au-rs
      - run: chmod +x ./hotprices-au-rs
      - run: ./hotprices-au-rs sync --quick woolies
      - name: Save cache of downloaded files on failure
        uses: actions/cache/save@v4
        if: failure()
        with:
          path: ./cache
          key: ${{ github.workflow }}-${{ github.job }}
      - uses: actions/upload-artifact@v4
        with:
          name: woolies_snapshot
          path: ./output/woolies/
  scrape-coles:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a release binary
        uses: actions/download-artifact@v4
        with:
          name: hotprices-au-rs
      - run: chmod +x ./hotprices-au-rs
      - name: Activate fetch cache for coles
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ github.workflow }}-${{ github.job }}
      - run: ./hotprices-au-rs --debug sync --quick coles
      - name: Save cache of downloaded files on failure
        uses: actions/cache/save@v4
        if: failure()
        with:
          path: ./cache
          key: ${{ github.workflow }}-${{ github.job }}
      - uses: actions/upload-artifact@v4
        with:
          name: coles_snapshot
          path: ./output/coles/
  merge-price-history:
    permissions:
      contents: read  # Required for checkout action
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    needs:
      - scrape-woolies
      - scrape-coles
    steps:
      - name: Download coles artifact
        uses: actions/download-artifact@v4
        with:
          name: coles_snapshot
          path: ./output/coles/
      - name: Download woolies artifact
        uses: actions/download-artifact@v4
        with:
          name: woolies_snapshot
          path: ./output/woolies/
      - name: Download a release binary
        uses: actions/download-artifact@v4
        with:
          name: hotprices-au-rs
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "${{ vars.TARGET_ROLE_ARN }}"
          aws-region: ap-southeast-2
      # Use "cp" because it is an error if the file doesn't exist. It means history
      # is broken and needs to be built from scratch locally.
      - run: aws s3 cp s3://grocery-scrape-au/latest-canonical.json.gz ./output/
      - run: chmod +x ./hotprices-au-rs
      - run: ./hotprices-au-rs analysis
      - uses: actions/upload-artifact@v4
        with:
          name: latest_canonical
          path: ./output/latest-canonical.json.gz
