name: Security audit
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 0 * * *'
jobs:
  audit:
    name: Run cargo audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # See https://github.com/rustsec/audit-check/pull/16
      - uses: clechasseur/rustsec-audit-check@b5ade62a8d38826bb50ca4b8b9bc2a8a97f0d44d
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
